---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      service: postgres
      type: backend
  template:
    metadata:
      labels:
        app: voting-app
        service: postgres
        type: backend
    spec:
      containers:
        - name: postgres
          image: postgres:12.11-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      service: redis
      type: backend
  template:
    metadata:
      labels:
        app: voting-app
        service: redis
        type: backend
    spec:
      containers:
        - name: redis
          image: redis:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      service: worker
      type: backend
  template:
    metadata:
      labels:
        app: voting-app
        service: worker
        type: backend
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      service: voting
      type: frontend
  template:
    metadata:
      labels:
        app: voting-app
        service: voting
        type: frontend
    spec:
      containers:
        - name: voting
          image: kodekloud/examplevotingapp_vote:v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      service: results
      type: frontend
  template:
    metadata:
      labels:
        app: voting-app
        service: results
        type: frontend
    spec:
      containers:
        - name: results
          image: kodekloud/examplevotingapp_result:v1