apiVersion: v1
kind: Pod
metadata:
  name: results-pod
  labels:
    app: voting-app
    service: results
    type: frontend
spec:
  containers:
  - name: results-app-container
    image: kodekloud/examplevotingapp_result:v1