apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    app: voting-app
    service: voting
    type: frontend
spec:
  containers:
  - name: voting-app-container
    image: kodekloud/examplevotingapp_vote:v1
