apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: voting-app
    type: backend
    service: worker
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1